/*
CREATE BIGFILE TABLESPACE PO_LAB4
  DATAFILE 'PO_LAB4.dat'
  SIZE 20M AUTOEXTEND ON;
*/

/*
CREATE USER c##PO_LAB4 IDENTIFIED BY PO_LAB4
  DEFAULT TABLESPACE PO_LAB4
  TEMPORARY tablespace TEMP
  QUOTA unlimited on PO_LAB4;
GRANT create session TO c##PO_LAB4;
GRANT create table TO c##PO_LAB4;
GRANT create view TO c##PO_LAB4;
GRANT create any trigger TO c##PO_LAB4;
GRANT create any procedure TO c##PO_LAB4;
GRANT create sequence TO c##PO_LAB4;
GRANT create synonym TO c##PO_LAB4;
*/

DROP SEQUENCE SEQ_RUN_ID;
DROP SEQUENCE SEQ_SCORE_ID;
DROP SEQUENCE SEQ_USER_ID;

DROP TABLE run CASCADE CONSTRAINTS;
DROP TABLE score CASCADE CONSTRAINTS;
DROP TABLE "User" CASCADE CONSTRAINTS;

CREATE TABLE run (
    run_id     NUMBER(10) NOT NULL,
    name       VARCHAR2(50) NOT NULL,
    "date"     TIMESTAMP NOT NULL,
    distance   NUMBER(10,3) NOT NULL
);
ALTER TABLE run ADD CONSTRAINT run_pk PRIMARY KEY ( run_id );

CREATE TABLE score (
    score_id       NUMBER(10) NOT NULL,
    time           INTERVAL DAY(0) TO SECOND(6) NOT NULL,
    user_id   	   NUMBER(10) NOT NULL,
    run_id     	   NUMBER(10) NOT NULL
);
ALTER TABLE score ADD CONSTRAINT score_pk PRIMARY KEY ( score_id );

CREATE TABLE "User" (
    user_id     NUMBER(10) NOT NULL,
    name        VARCHAR2(50) NOT NULL,
    last_name   VARCHAR2(50) NOT NULL,
    login       VARCHAR2(50) NOT NULL,
    pwd         VARCHAR2(50) NOT NULL,
	user_type	NUMBER(1) NOT NULL
);
ALTER TABLE "User" ADD CONSTRAINT user_pk PRIMARY KEY ( user_id );

ALTER TABLE score
    ADD CONSTRAINT score_run_fk FOREIGN KEY ( run_id )
        REFERENCES run ( run_id )
		ON DELETE CASCADE;
		
ALTER TABLE score
    ADD CONSTRAINT score_user_fk FOREIGN KEY ( user_id )
        REFERENCES "User" ( user_id )
		ON DELETE CASCADE;
		
CREATE SEQUENCE SEQ_RUN_ID MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION;
CREATE SEQUENCE SEQ_SCORE_ID MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION;
CREATE SEQUENCE SEQ_USER_ID MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION;

/*
CREATE OR REPLACE TRIGGER TR_INS_RUN 
BEFORE INSERT ON RUN
FOR EACH ROW
BEGIN
  :NEW.RUN_ID:=SEQ_RUN_ID.nextval;
END;
*/

/*
CREATE OR REPLACE TRIGGER TR_INS_SCORE 
BEFORE INSERT ON SCORE
FOR EACH ROW
BEGIN
  :NEW.SCORE_ID:=SEQ_SCORE_ID.nextval;
END;
*/

/*
CREATE OR REPLACE TRIGGER TR_INS_USER 
BEFORE INSERT ON "User"
FOR EACH ROW
BEGIN
  :NEW.USER_ID:=SEQ_USER_ID.nextval;
END;
*/

INSERT INTO "User" (name,last_name,login,pwd,user_type) VALUES('Wojciech','Grzyb','admin','admin',1);